on: [push]
jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      matrix_list: ${{ steps.create.outputs.matrix_list }}
    steps:
      - id: create
        run: echo 'matrix_list=[ 0, 1, 2, 3 ]' >> "$GITHUB_OUTPUT"
  test:
    needs: create
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.setup.outputs.matrix_list }}"
  run:
    needs: create
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: ${{ fromJson(needs.create.outputs.matrix_list) }}
    steps:
      - run: echo "${{ matrix.id }}"
